title: MÃ³j blog
description: Long Form Jekyll theme built with SASS

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

timezone: Europe/Warsaw
locale: pl_PL

navigation:
    - title: Blog
      url: /index.html
    - title: Kontakt
      url: /contact

social:
    github: ta3k
    instagram: mrtaczyk
    facebook: maciej.karaszewski
    email: maciej.m.karaszewski@gmail.com
    linkedin: maciej.karaszewski
    youtube: MrTaczyk
    tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
